#!/bin/sh

for f in $(git diff --cached --name-status | grep ^A | cut -c2-); do
	if ! [[ $f =~ "*\\.\\*" ]]; then
		echo "Ashar: \"Do not commit executable files! Please remove them from the commit.\""
		exit 1
	fi
done
